export const IS_AUTHENTICATED = "IS_AUTHENTICATED";
export const LOG_OUT = "LOG_OUT";

export const CREATE_ACCOUNT_SUCCESS = "CREATE_ACCOUNT_SUCCESS";
export const GET_USER_INFORMATION = "GET_USER_INFORMATION";

export const REQUEST_RESET_SUCCESS = "REQUEST_RESET_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";

export const CLEAR_ERROR_MESSAGE = "CLEAR_ERROR_MESSAGE";
export const DISPLAY_ERROR_MESSAGE = "DISPLAY_ERROR_MESSAGE";

export const DONATE_SUCCESS = "DONATE_SUCCESS";

export const GET_PROFILE_PENDING = "GET_PROFILE_PENDING";
export const GET_PROFILE_FULFILLED = "GET_PROFILE_FULFILLED";
export const GET_PROFILE_REJECTED = "GET_PROFILE_REJECTED";

export const VOTE_PENDING = "VOTE_PENDING";
export const VOTE_FULFILLED = "VOTE_FULFILLED";
export const VOTE_REJECTED = "VOTE_REJECTED";

export const STATUS_STREAM = "STATUS_STREAM";
export const GET_CONTESTANTS = "GET_CONTESTANTS";
export const UPDATE_PROFILE = "UPDATE_PROFILE";

export const VERIFY_USERNAME_PENDING = "VERIFY_USERNAME_PENDING";
export const VERIFY_USERNAME_FULFILLED = "VERIFY_USERNAME_FULFILLED";
export const VERIFY_USERNAME_REJECTED = "VERIFY_USERNAME_REJECTED";

